// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SA_simple
arma::mat SA_simple(arma::mat ocData, double maxInt, double momentum);
RcppExport SEXP _rELA_SA_simple(SEXP ocDataSEXP, SEXP maxIntSEXP, SEXP momentumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ocData(ocDataSEXP);
    Rcpp::traits::input_parameter< double >::type maxInt(maxIntSEXP);
    Rcpp::traits::input_parameter< double >::type momentum(momentumSEXP);
    rcpp_result_gen = Rcpp::wrap(SA_simple(ocData, maxInt, momentum));
    return rcpp_result_gen;
END_RCPP
}
// SA
arma::mat SA(arma::mat ocData, arma::mat envData, double maxInt, double momentum);
RcppExport SEXP _rELA_SA(SEXP ocDataSEXP, SEXP envDataSEXP, SEXP maxIntSEXP, SEXP momentumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ocData(ocDataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type envData(envDataSEXP);
    Rcpp::traits::input_parameter< double >::type maxInt(maxIntSEXP);
    Rcpp::traits::input_parameter< double >::type momentum(momentumSEXP);
    rcpp_result_gen = Rcpp::wrap(SA(ocData, envData, maxInt, momentum));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rELA_SA_simple", (DL_FUNC) &_rELA_SA_simple, 3},
    {"_rELA_SA", (DL_FUNC) &_rELA_SA, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rELA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
