# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SA_simple <- function(ocData, maxInt = 50000, momentum = 0.3) {
    .Call('_rELA_SA_simple', PACKAGE = 'rELA', ocData, maxInt, momentum)
}

SA <- function(ocData, envData, maxInt = 50000, momentum = 0.3) {
    .Call('_rELA_SA', PACKAGE = 'rELA', ocData, envData, maxInt, momentum)
}

